preload=/home/enainandreev/.config/hypr/wallpapers/black_2.jpg
preload=/home/enainandreev/.config/hypr/wallpapers/bg_wallpaper_2.jpg
wallpaper {
    monitor = eDP-1
    path = /home/enainandreev/.config/hypr/wallpapers/bg_wallpaper_2.jpg
    fit_mode = cover
}