preload=/home/enainandreev/.config/hypr/wallpapers/black.png
preload=/home/enainandreev/.config/hypr/wallpapers/bg_wallpaper.jpg
wallpaper {
    monitor = eDP-1
    path = /home/enainandreev/.config/hypr/wallpapers/bg_wallpaper.jpg
    fit_mode = cover
}